### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/warframe-worldstate-data#11]
Validate each JSON file is valid JSON.

**Comment by dbarbuzzi** [comment]
Given the age of this, I wanted to ask before I get started – would you be open to review and accept a PR for this? Assuming yes, can I contact you at your profile email to ask a few questions about my intended approach as there are a lack of precedents to follow in the repo?

**Comment by TobiTenno** [comment]
Yes

**Comment by TobiTenno** [comment]
Closing: completed with #37
