### ISSUE TITLE
Nodes wrong after Disruption update

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [WFCD/warframe-worldstate-data#129]
Missing: `SolNode308` which is `Apollo (Lua)` disruption

Wrong: `SolNode118`, `SolNode30`, `SolNode188`, `SolNode745`, all of which were changed to Disruption by DE

Maybe wrong: `SolNode87` is listed as `Ancient Retribution`? That's Ganymede which is also Disruption but there's also four event nodes for Ganymede, all of which are Disruption, so for all I know it's right

**Comment by TobiTenno** [comment]
feel free to update them. I haven't changed most of them in some time. if not, I'll update them when I can.

**Comment by TobiTenno** [comment]
closed with 13d2a016935dfeeff537fd6a0dc23d424ec4f2ef
