### ISSUE TITLE
New NPM version

### ISSUE THREAD

**Issue by sethkinast** [WFCD/warframe-worldstate-data#17]
Hey guys,

Would you mind pushing a 0.0.4 to NPM when you have a chance? Lots of new data since the last time it was published as 0.0.3.

Thanks! :)

**Comment by aliasfalse** [comment]
the recommendation from us is to use the git repo instead of the published npm package, because we do add new strings so often

**Comment by aliasfalse** [comment]
npm i -S git://github.com/wfcd/warframe-worldstate-data.git

**Comment by sethkinast** [comment]
Yep that's actually what I'm doing. Cool, I'll keep doing that then. Maybe a README note?

**Comment by aliasfalse** [comment]
sure
