### ISSUE TITLE
wrong node mission types

### ISSUE THREAD

**Issue by viseyth** [WFCD/warframe-worldstate-data#18]
multiple mission types have since changed and are outdated.
so far, i have found:

- Everest (Earth), an Excavation
- Cervantes (Earth), a Sabotage
- E Prime (Earth), an Exterminate
- Ultor (Mars), a Crossfire
- Martialis (Mars), a Rescue
- Stephano (Uranus), a Defense
- Mithra (Void), an Interception

**Comment by aliasfalse** [comment]
feel free to fix it and submit a pull request, or i'll do it when i get a chance.

**Comment by aliasfalse** [comment]
fixed
