### ISSUE TITLE
Seems like the Kuva Mission needs to change the source

### ISSUE THREAD

**Issue by sctop** [WFCD/warframe-worldstate-data#197]
Recently I realized that there are no Kuva missions available for those tools using this API. After a quick read I found that the current source URL can't be used anymore, and it has been moved to [here](https://10o.io/kuvalog.json).
Not pretty sure if the data is correct or real-time, but it should be the same as you guys used before.

Thanks.

**Comment by TobiTenno** [comment]
if you search in that file, there's no "KuvaMissions" missions, which is how we distinguish arbis from kuva missions...

even semlar's own site took down their kuva section.

tl;dr: I'd love to, i just don't know where from or which data now represents it.
