### ISSUE TITLE
Wrong format

### ISSUE THREAD

**Issue by FlorianDewulf** [WFCD/warframe-worldstate-data#22]
Hi,

I was using the branch "l10n" to have resources for a bot I am creating, and I want to thanks you for this wonderful repo.
I found an issue with the format of the file "warframe-worldstate-data/data/sortieData.json".
In the data folder, the file follows the format : 
`
{
  "endStates" : [
    ...
  ],
  "modifiers" : [
    ...
  ]
}
`

But this format doesn't match with the files in the language folders.  It is not usable with the data retrieve from the API currently.

Btw you should export the different folders in the export.js so people would be able to import your library and select the language. It's easy to do, you require the folder name it will automatically call the index.js inside which export all the jsons.

**Comment by aliasfalse** [comment]
It's a branch, don't pull from a dev branch that is way behind, lol

**Comment by FlorianDewulf** [comment]
"that is way behind" => The last commit is 4 days ago, on the master it's 7 days ago. Didn't know it was a "dev branch". Meh.

Btw I choose this branch because of the name and because I wanted the informations but for another language than english. I saw the directories and the translated files so I was more interesting by this one (but I didn't test it until today and I didn't go deep into the code).

Thanks for your quick answer, do you know when the other languages will be available ?

**Comment by aliasfalse** [comment]
I can't say for sure. I'm behind on some fixes for WFCD/genesis first, then i need to prep the i10n on that one, then i'll be back on this for a bit

Sadly I have a lot on my plate. I've been trying to find some good contributors to help me bring this one up to date.

**Comment by aliasfalse** [comment]
It would be welcome
