### ISSUE TITLE
languages.json missing an entry

### ISSUE THREAD

**Issue by Hellsing** [WFCD/warframe-worldstate-data#23]
My program just ran into key not found exception:

> Languages[]: Key not found: /Lotus/StoreItems/Types/Recipes/Helmets/MonkeyKingAltBHelmetBlueprint

This is the key for the WUKONG MACAK HELMET BLUEPRINT entry.

![Alert](http://puu.sh/y4zwI/2ebbb843e7.png "Alert")

**Comment by aliasfalse** [comment]
I'd recommend checking out the safe handling for it that we do on warframe-worldstate-parser

**Comment by aliasfalse** [comment]
But I will get this added in a few hours

**Comment by aliasfalse** [comment]
added
