### ISSUE TITLE
languages.json extra wrapper

### ISSUE THREAD

**Issue by msaracevic** [WFCD/warframe-worldstate-data#30]
I am actually using `languages.json` in my project as well. The issue I have with it is that it has only couple of places where the actual key has an actual object attached.

Example (desc appears only 4 times): 
```
  "/lotus/language/items/kelaeventdogtagname": {
    "desc": "To be delivered to Steel Meridian or chosen Syndicate in the relay.",
    "value": "RATHUUM PRISONER COORDINATES"
  }
```
In 99% of cases it is just value.

My suggestion is to change it into key: value pair, so in following format:
```
  "/lotus/language/infestedplainsevent/infestedplainsbountyname": "Plague Star",
```

Benefits would be smaller file, easier to maintain and most importantly, me not having to readjust it to shamelessly take it into my project.

Cons are that this would be breaking change, since all the other tools depending on this would fail since you change the structure.

**Comment by TobiTenno** [comment]
That's not something I'm really prepared or willing to change. The largest breaking aspect of it is that we use it in wfcd/warframe-worldstate-parser assuming the value, and changing it to this can be problematic, as well as in wfcd/warframe-status

It doesn't really change the maintainability, but this would also reduce the readability, while removing all of the opportunities for additional values as in the example you gave. It may only appear 4 times, but it was designed this way on purpose.

In your case, i don't think it would take long to change yours by just adding a `.value` to each instance of `languages[key]`, if i understand how you are also consuming a similar file.

Alternatively, you could simply use our api at `https://api.warframestat.us/languages/search/{key}`, which will return an array of objects specific to your search, if you feel like going a route where you don't have to update npm to get new strings.

**Comment by msaracevic** [comment]
Sure thing, I understand your point of view, let's close the matter

**Comment by TobiTenno** [comment]
I'm more than happy to talk through it if you think it's easy enough to switch to it.

**Comment by msaracevic** [comment]
I've sent you message on discord
