### ISSUE TITLE
[Bug]: Tracker displays disruption arbitrations as being spy.

### ISSUE THREAD

**Issue by Rasalhage** [WFCD/warframe-worldstate-data#304]
### Summary

Tracker displays disruption arbitrations as being spy.
![image](https://user-images.githubusercontent.com/42392355/135738282-6a0d7521-fbd6-4f3c-85c7-c99db346d80c.png)
![image](https://user-images.githubusercontent.com/42392355/135738290-03c9fc7f-2259-4871-8ba9-a34db5ab0d4a.png)

### Version

hub (Default)

### What browsers are you seeing the problem on?

Opera

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TobiTenno** [comment]
closed with 0a42bf22fb763260daa912ef1f6d7817cb206cea once it propagates to the api.
