### ISSUE TITLE
Relics

### ISSUE THREAD

**Issue by hitokiri** [WFCD/warframe-worldstate-data#39]
Hello, the area of the relics, does not return anything

**Comment by TobiTenno** [comment]
hi can you be more specific?

**Comment by TobiTenno** [comment]
why would it?

**Comment by TobiTenno** [comment]
oh, i see the confusion, it's been empty for some time. that was removed and I hadn't updated the docs. sorry.

**Comment by TobiTenno** [comment]
I've removed the confusing line in the README. We used to manually enter that data, but haven't for a long time. I use https://api.warframestat.us/drops/search/axi%20v1 if i need what's in a particular relic now, or to find where one drops
