### ISSUE TITLE
Fissure Enemy & Mission Types Inconsistent

### ISSUE THREAD

**Issue by Defaultldentity** [WFCD/warframe-worldstate-data#43]
in /data/solNodes.json:

```
  "SolNode16": {
    "value": "Augustus (Mars)",
    "enemy": "Crossfire",
    "type": "Rescue"
},
```
It is (now) Excavation-Grineer on the solar map. I wonder whether it was a mistake initially, or DE have changed this node? (Does this happen?)

**Comment by Defaultldentity** [comment]
I have noticed that when fissure event at warframestat.us was wrong. Meanwhile, worldState.php had `MT_EXCAVATE` explicitly set (see below). Maybe, for fissure data, this value should take precedence. Also, it might make sense to report inconsistencies between `MT_*` value in worldState.php json, and raw `SolNode*` data, in case they happen in future

```json
{
"_id":{"$oid":"5bc06435ff3e2ea88666a3d6"},
"Region":4,"Seed":17782,
"Activation":{"$date":{"$numberLong":"1539335221911"}},
"Expiry":{"$date":{"$numberLong":"1539340369368"}},
"Node":"SolNode16",
"MissionType":"MT_EXCAVATE",
"Modifier":"VoidT1"
}
```

**Comment by Defaultldentity** [comment]
```
  "SolNode28": {
    "value": "M Prime (Mercury)",
    "enemy": "Grineer",
    "type": "Sabotage"
},
```

This one is also wrong/outdated. It has now mission type `Crossfire Exterminate`, faction `Grineer vs Infestation`. There might be more

**Comment by TobiTenno** [comment]
Feel free to update [wfcd/warframe-worldstate-parser](https://github.com/WFCD/warframe-worldstate-parser/blob/master/lib/Fissure.js#L37) to use the specified enemy mission type from the fissure data. This is updated from the last time I altered these.

As for the SolNode data, it's not something they provide in a programmatic manner, so we have to update those manually.
