### ISSUE TITLE
Most keys in languages.json are in lowercase

### ISSUE THREAD

**Issue by yorushika** [WFCD/warframe-worldstate-data#50]
For example, these are some content of `languages.json`:

```
  "/lotus/types/items/miscitems/neuralsensor": {
    "value": "Neural Sensors"
  },
```

I converted this json to a dictionary of Python, and it works fine.
But when I read official world state API, I got this:

`"/Lotus/Types/Items/MiscItems/NeuralSensor"`

So this *key* cannot match any value of that dictionary above.

Though I can just use `lower()` function when using the key, but some keys in the dictionary contain characters in uppercase. That's too bad.

Can you make some fix of this?

**Comment by TobiTenno** [comment]
all of them are in lowercase
we're not gonna change it.
