### ISSUE TITLE
Header "value" should not be included in Conclave Challenges.

### ISSUE THREAD

**Issue by VaslD** [WFCD/warframe-worldstate-data#86]
The entry marked with `rootChallenge` in Conclave Challenges seems to be a header (category/set description).

Currently it's:
```javascript
    {
        "id": "5c948ca1dba6feda92ea884d",
        "description": "the standard set of weekly challenges",
        "expiry": "2019-03-29T07:20:01.205Z",
        "amount": 0,
        "mode": "None",
        "category": "week_root",
        "eta": "4d 3h 23m 39s",
        "expired": false,
        "daily": false,
        "rootChallenge": true,
        "endString": "4d 3h 23m 39s",
        "asString": "the standard set of weekly challenges on None 0 times in a week_root"
    }
```

It's been like this for as long as I'm using WarframeStat.us. Very confusing (I think "asString" made it worse) so I only figured it out today.

This should probably be removed (along with "rootChallenge" flag if not used elsewhere) because they serve (seemingly) no purpose. The **description of ALL items in the list** should not be included as **AN item in the list**.

There's gotta be a better way to do this if the info was somehow needed. One solution I can think of is to move this node up a level out of the list of challenges, making the result JSON a tree-like (not technically) structure instead of (currently) a flat-list.

**Comment by TobiTenno** [comment]
This data is generated by worldstate parser, not data, and your can filter whatever your like on the consumer side. I try to provide as much data as was in the original as I can.

**Comment by TobiTenno** [comment]
The root challenge is a grouper that exists in DE's data, it's more something that's added in.
